version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.16.1
    volumes:
      - ./config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./docker_volumes/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "elastic"
      discovery.type: single-node
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
  tomee:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - "8080:8080"
    networks:
      - elk
  npm:
    build:
      context: ./untitled1
      dockerfile: Dockerfile
    depends_on:
      - tomee
    ports:
      - "3000:3000"
    networks:
      - elk
networks:
  elk: